### ISSUE TITLE
cannot import name 'dedent' from 'matplotlib.cbook'

### ISSUE THREAD

**Issue by carballada** [wmpg/WesternMeteorPyLib#9]
Dear Denis, on a fresh installtion on w10 I received the following error

(wmpl) PS D:\RMS_soft\WesternMeteorPyLib> python -m wmpl.Formats.CAMS --help
Traceback (most recent call last):
  File "C:\Users\carba\Anaconda3\envs\wmpl\lib\runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\carba\Anaconda3\envs\wmpl\lib\runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "D:\RMS_soft\WesternMeteorPyLib\wmpl\__init__.py", line 35, in <module>
    module = loader.find_module(module_name).load_module(module_name)
  File "D:\RMS_soft\WesternMeteorPyLib\wmpl\CAMO\MarkFragments.py", line 12, in <module>
    from wmpl.Formats.Met import loadMet
  File "D:\RMS_soft\WesternMeteorPyLib\wmpl\Formats\Met.py", line 13, in <module>
    from wmpl.Trajectory.Trajectory import Trajectory
  File "D:\RMS_soft\WesternMeteorPyLib\wmpl\Trajectory\Trajectory.py", line 26, in <module>
    Basemap = importBasemap()
  File "D:\RMS_soft\WesternMeteorPyLib\wmpl\Utils\OSTools.py", line 49, in importBasemap
    from mpl_toolkits.basemap import Basemap
  File "C:\Users\carba\Anaconda3\envs\wmpl\lib\site-packages\mpl_toolkits\basemap\__init__.py", line 50, in <module>
    from .proj import Proj
  File "C:\Users\carba\Anaconda3\envs\wmpl\lib\site-packages\mpl_toolkits\basemap\proj.py", line 6, in <module>
    from matplotlib.cbook import dedent
ImportError: cannot import name 'dedent' from 'matplotlib.cbook' (C:\Users\carba\Anaconda3\envs\wmpl\lib\site-packages\matplotlib\cbook\__init__.py)

could you help me?   
thank you in advace!

**Comment by dvida** [comment]
Please see the troubleshooting section in README, you will have to install an old versinon of matplotlib.

**Comment by markmac99** [comment]
I agree with the reason this has been closed, but i would like to suggest we should also consider changes to the libraries to use the latest version of Basemap. I'd be happy to investigate this.

**Comment by dvida** [comment]
Hi Mark,
that would be great, you have my full support! 
I would love to move away from basemap, but cartopy simply does not have the basic functionality that basemap had.
